#!/bin/bash

# Source app helpers
source _common.sh
source /usr/share/yunohost/helpers
# Exit on command errors and treat unset variables as an error
ynh_abort_if_errors

# ========================================
# Retrieve arguments from the manifest
# ========================================
domain=$YNH_APP_ARG_DOMAIN 
path_url=$YNH_APP_ARG_PATH
password=$YNH_APP_ARG_PASSWORD
is_public=$YNH_APP_ARG_IS_PUBLIC
admin=$YNH_APP_ARG_ADMIN
# Get multi-instances specific variables
app=$YNH_APP_INSTANCE_NAME
app_nb=$YNH_APP_INSTANCE_NUMBER
# Generate a unique username
user="${app}__${app_nb}"

# ========================================
# CHECKS
# ========================================

# Check destination directory
final_path="/var/www/${app}"
test ! -e "$final_path" || ynh_die "This path already contains a folder"
# Normalize the url path syntax
path_url=$(ynh_normalize_url_path $path_url)
# Path availability
ynh_webpath_available $domain $path_url
# Register web path
ynh_webpath_register $app $domain $path_url

# ========================================  
# Store app settings
# ========================================  

ynh_app_setting_set $app domain $domain
ynh_app_setting_set $app path $path_url
ynh_app_setting_set $app is_public $is_public
ynh_app_setting_set $app final_path $final_path
ynh_app_setting_set $app user $user
ynh_app_setting_set $app admin $admin
ynh_app_setting_set $app password $password

# ========================================
# INSTALLATION
# ========================================

echo "Begin installation..." >&2
# Check dependencies
ynh_install_app_dependencies python3 python3-venv git
# Create user account
ynh_system_user_create $user

# ========================================
# DJANGO APPLICATION SETUP
# ========================================

echo "Setup django project..." >&2
# Create virtual environnement
venv_setup $final_path
# Install required pip packages
venv_pip install django gunicorn
# Setup new Django project
django_setup_project $final_path
echo "Done." >&1

# ========================================
# SPECIFIC TO APP SETUP
# ========================================

echo "Setup application..." >&2
# Import urls and settings from 'django/' 
django_setup_settings_and_urls
# Install additionnal packages
venv_pip install -r ../django/requirements.txt
# Copy embedded modules
django_install_from_folder 'core'
# Collect static files
venv_activate
django-admin collectstatic
venv_deactivate

# ========================================
# POST INSTALL
# ========================================

echo "Finalizing..." >&2
# Set permissions
sudo chown -hR "${user}:" $final_path

# ========================================
# SERVICES
# ========================================

echo "Services setup..." >&2
# Use socket file
socket_name="gunicorn.sock"
netloc="unix:${django_path}/${socket_name}" 

# Set nginx configuration
ynh_replace_string "__NETLOC__" $netloc ../conf/nginx.conf
ynh_add_nginx_config

# Set gunicorn service configuration
ynh_replace_string "__NETLOC__" $socket_name ../conf/systemd.service
ynh_replace_string "__APPUSER__" $user ../conf/systemd.service
ynh_add_systemd_config
service $app restart
