#!/bin/bash

# Get multi-instances specific variables
app=$YNH_APP_INSTANCE_NAME
app_nb=$YNH_APP_INSTANCE_NUMBER

# Source app helpers
. /usr/share/yunohost/helpers

# Retrieve app settings
domain=$(ynh_app_setting_get "$app" domain)
user=$(ynh_app_setting_get "$app" user)
final_path=$(ynh_app_setting_get "$app" final_path)

# TODO: Kill the gunicorn service

# Delete app directory and configurations
ynh_secure_remove "$final_path"
ynh_remove_nginx_config
ynh_remove_system_config

# Remove the user account
ynh_system_user_delete $user
